salesforcecli/sfdx-cli

.gitignore, package.json, scripts/test/coverage, src/updateReachability.test.ts, yarn.lock
=> chore: migrate plugin-telemetry [ci-skip]

README.md
What does this PR do?
adds info to the readme about latest-rc
What issues does this PR fix or reference?
@W-8668388@
=> fix: [skip-ci] update readme with latest-rc install info

.gitignore, package.json, src/cli.ts, src/hooks/updateReachability.ts, src/lazyRequire.test.ts, src/updateReachability.test.ts, src/verifyPluginVersion.test.ts, yarn.lock
Update node version and dependencies.
@W-8485419@
=> feat: update node version

DEVELOPER.md
Update developer.md
@W-8485419@
=> chore: update md

command-snapshot.json, package.json, src/hooks/preupdate.ts, yarn.lock
Releases sfdx-cli v7.88.0
@W-8875747@
=> chore: release version 7.88.0

.circleci/config.yml
=> build: use linux executor from CI orb

.circleci/config.yml, package.json, scripts/windows/setup_signing_key
Reverts salesforcecli/sfdx-cli#40
=> chore: revert "build: sign windows exe"

.circleci/config.yml, package.json
Add macOS pack & uploading CI job
[@W-8886491@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B00000096Wm6IAE/view?ws=%2Flightning%2Fr%2FADM_Sprint__c%2Fa0lB00000027RQmIAM%2Fview)
=> build: add macOS pkg pack & upload CI job

.circleci/config.yml, package.json
Windows installers should be signed with these changes and some changes made in circle ci.
@W-8886441@
=> chore: add support for signing windows installers

.circleci/config.yml, SCRIPTS.md, scripts/promote, scripts/promote-stable-rc
Fixes the mac and promote jobs.
N/A
=> chore: update circle scripts @W-0@

package.json
Bump version to 7.93.0 latest-rc
=> chore: bump version to 7.93.0 latest-rc

package.json
Move shx to devdep
@W-8856274@
=> chore: move sxh to dev-dep

scripts/promote
=> fix: promote script [skip ci]

Questions
This file shouldn't be in the repo.
=> Delete Questions [skip-ci][skip-validate-pr]

.circleci/config.yml
moves cron time so it runs (didn't get merged yesterday)
@W-0@
=> chore: merge for cron deadline

.circleci/config.yml, scripts/run-plugin-nuts.js
fixes a couple of bugs encountered after full run done
=> chore: fixing bugs

scripts/monitor-plugin-nuts.js
ensure exceptions don't short circuit monitor
=> chore: ensure exceptions don't short circuit monitor

.circleci/config.yml, scripts/promote-rc-to-latest
uses stable-rc buildManifest to get version/sha.  Remove manual work
it's related to @W-9209891@ but is only a small part
=> chore: promote from manifest

package.json, yarn.lock
Bump version for latest-rc to 7.103.0
@W-0@
=> chore(latest-rc): bump to 7.103.0

command-snapshot.json, package.json, yarn.lock
Bump version to 7.104.0 for latest release
@W-0@
=> chore(latest-rc): bump to 7.104.0

scripts/promote-dist-tags
=> chore: don't promote salesforcedx

package.json, src/cli.ts, yarn.lock
Adding More Information for Version Command.
Added new options[ --verbose , --json] to the Version command which provides information of CLI Version, Plugin Version, OS and its version
@W-8682815@
=> feat: add more version information

.circleci/config.yml
=> chore: eRelease 7.112.0

.circleci/config.yml, package.json, yarn.lock
=> chore(latest-rc): bump to 7.112.1

.circleci/config.yml
dependabot automerge
@W-8776229@
=> chore: dependabot automation

package.json, yarn.lock
=> chore(latest-rc): bump to 7.117.0

package.json
adds a repository property on package.json so dependabot-automerge job can work.
@W-8776229@
=> chore: dependabot automation uses the repository prop

command-snapshot.json, package.json, yarn.lock
Remove plugins from list so that `oclif` doesn't try to load it
@W-9642529@
=> chore: remove unused plugin

.circleci/config.yml
Verify node installation in docker full images, also add `SFDX_CLI_VERSION`, hopefully this should fix all our docker jobs when releasing.
@W-9861521@
=> fix: verify node installation in docker full image

package.json, yarn.lock
=> chore(latest-rc): bump to 7.119.0

package.json, yarn.lock
=> chore(latest-rc): bump to 7.119.1

src/hooks/verifyPluginVersion.ts, src/verifyPluginVersion.test.ts
Does not allow users to install `sfdx-cli` as a plugin
@W-9822488@
=> fix: do not allow installation of banned plugins

package.json, yarn.lock
=> chore(latest-rc): bump to 7.119.2

package.json, yarn.lock
=> chore(latest-rc): bump to 7.119.3

package.json, yarn.lock
=> chore(latest-rc): bump to 7.121.0

package.json, yarn.lock
add resolution for templates
@W-9976179@
=> fix: add resolution for templates

package.json
=> chore(latest-rc): bump to 7.121.2

scripts/monitor-plugin-nuts.js, scripts/run-plugin-nuts.js
Adds checks to ensure env var token is set for just-nuts scripts.
@W-9299600@
=> chore(just-nuts): ensure token env var is set

.vscode/launch.json, command-snapshot.json, package.json, yarn.lock
=> Release v7.129.0 as latest-rc

.circleci/config.yml, package.json
use yarn resolutions for STL
the reason @W-10458781@ didn't get shipped when we thought it would
=> chore: resolutions for stl

package.json, yarn.lock
=> chore: remove core and dedupe lock

package.json, yarn.lock
=> Release v7.138.1 as latest-rc

command-snapshot.json, package.json, yarn.lock
=> chore(latest-rc): bump to 7.141.1

.circleci/config.yml
=> chore: promote rc

.circleci/config.yml
Reverts salesforcecli/sfdx-cli#509
=> Revert "chore: promote rc"

scripts/promote-rc-to-latest
restore xz version file and promotes
=> fix: promote xz

package.json
Pack and upload `.xz` tarballs
=> fix: add xz

.circleci/config.yml, package.json, yarn.lock
=> chore(latest-rc): bump to 7.142.1

command-snapshot.json, package.json, yarn.lock
=> chore: bump alm

scripts/promote-stable-rc-tarballs
=> fix: xz on the promotes to rc

.circleci/config.yml, package.json, yarn.lock
Building new latest-rc with downgraded plugin-config [skip-validate-pr]
=> chore(latest-rc): bump to 7.146.1 and downgrade plugin-config

.circleci/config.yml
=> chore: use release context

.circleci/config.yml, package.json
another release since installer builds failed
=> chore(latest-rc): bump to 7.148.1

.circleci/config.yml, package.json
redo release for windows signing context requirements
=> chore(latest-rc): bump to 7.148.2

.circleci/config.yml
adds the release context (2 CTC envs moved there)
=> ci: fix context for promote

package.json, yarn.lock
bumps salesforce-alm for latest-rc 155.1
=> chore: bump salesforce-alm for packaging fixes

package.json, yarn.lock
=> chore: parking-orbit apex, test for pack tarballs

package.json, yarn.lock
=> chore(latest-rc): bump to 7.158.1

scripts/run-plugin-nuts.js
the lwc test plugin does not have homepage attr in package.json. Added an exception to script that launches all nut jobs for cli plugins.
@W-0@
=> chore: fix run all nuts

.github/workflows/announceRC.yml
sends release info to a slack workflow
=> ci: internal announcement of new version

package.json, yarn.lock
=> Release v7.164.1 as latest-rc

.github/workflows/promoteRCtoLatest.yml
Updates the slack post and channel for promote
@W-123123123@
=> Update promote announcement

.github/workflows/releaseFail.yml
failures for various cli release/promote workflows
=> ci: release fail notifications

.github/workflows/dockerBuildSlim.yml, .github/workflows/justNut.yml, .github/workflows/promote.yml, .github/workflows/promoteRCtoLatest.yml, .github/workflows/rcBuild.yml, package.json, yarn.lock
bump eslint-plugin-jsdoc, switch pipeline to lts/*
=> chore: bump eslint-plugin-jsdoc, switch pipeline to lts/*

.github/workflows/justNut.yml
retries on just-nuts
@W-12084293@
=> test: just-nuts retry like normal nuts

package.json, yarn.lock
=> Release v7.180.0 as latest-rc

.github/workflows/makePRforRC.yml, .github/workflows/rcTagAndRelease.yml
Makes changes to the latest-rc build process to work with changes in plugin-release-management
https://github.com/salesforcecli/plugin-release-management/pull/610/
[@W-12184428@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-12184428)
=> Update latest-rc release workflows

.github/workflows/make-pr-for-nightly.yml
What does this PR do?
Workflow to open a new nightly PR every night.
What issues does this PR fix or reference?
@W-12181871@
=> Nightly cron workflow

.github/workflows/promoteRCtoLatest.yml
Retries promote verify since the s3 cache can cause this to fail 
[@W-12406088@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-12406088)
Screenshot showing this works locally
=> Promote verify retries

package.json
add an sf plugin via JIT
open questions: 
does the build script that bumps pinnedDeps also bump JIT?
do I need to include it as a dependency, or as a devDependency, or something else besides this?
@W-12437610@
=> feat: add plugin-sobject via jit

package.json, src/help/sfdxCommandHelp.ts, src/help/sfdxHelp.ts, src/hooks/displayReleaseNotes.ts, src/hooks/incomplete.ts, src/hooks/postupdate.ts, src/hooks/salesforcedx-check.ts, yarn.lock
Uses sf-plugins-core v2 and oclif/core v2
@W-10791948@
=> feat: use oclif/core v2

package.json, yarn.lock
Removes the `salesforce-alm` plugin.  All remaining commands from this plugin are legacy and have equivalents in other open source plugins.
@W-10833257@
=> chore: remove toolbelt

.github/workflows/just-nuts.yml
remove toolbelt nuts exclusion and add plugin packaging nuts to the just-nuts workflow
@W-00000000@
=> chore: remove toolbelt nuts exclusion and add plugin packaging nuts to just-nuts

package.json
=> chore: pin oclif/core

package.json, yarn.lock
=> fix: bump sf-release

.github/workflows/create-cli-release.yml, .github/workflows/promote.yml
Forgot to push these changes to https://github.com/salesforcecli/sfdx-cli/pull/972
[@W-12587062@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-12587062)
=> Adds retries, correct runners, and prerelease ignore

.github/workflows/create-cli-release.yml, .github/workflows/just-nut.yml, .github/workflows/make-pr-for-nightly.yml, .github/workflows/promote-rc-to-latest.yml, .github/workflows/validate-pr.yml, scripts/verify-promote
Cleans up GHA that I noticed while migrating `sf` to deliver `nightlies`
[@W-12949193@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-12949193)
=> GHA cleanup

.github/workflows/just-nut.yml
retries 2 setup tasks for just-nuts
https://github.com/salesforcecli/sfdx-cli/actions/runs/4857041974/jobs/8657551687#step:4:1
=> fix: retry cli install and yarn

.github/workflows/create-github-release.yml
=> chore: prerelase branch glob

dockerfiles/Dockerfile_full, dockerfiles/update-docker-node-version.js
Use the full node version off of the process instead up just the major
QA: 
=> Use full version installed for Dockerfile
