scripts/promote
scripts/promote-stable-rc

fixes git case issue 
@W-0000000@

fix: promote scripts uses HEAD

---

scripts/promote-stable-rc

read version from package.json as the version tag does not yet exist
@W-0000000@

fix: read version from package.json for promote-stable-rc

---

scripts/run-plugin-nuts.js

Add an additional parameter to script that triggers just-nuts that passes along the npm module name, which will be used in target jobs to checkout the source branch to be used in tests. This is specifically to solve an issues with lerna repos.
@W-9167855@

chore: add module name to data used to run just-nuts

---

src/hooks/verifyPluginVersion.ts

checks to see if people are installing salesforcedx and gives them an error message if they are (running this as a preinstall script in npm from the salesforcedx plugin didn't produce a warning).
@W-9300521@

chore: salesforcedx install warning

---

.circleci/config.yml
package.json
yarn.lock

1. re-release RC for toolbelt fix
2. limit to node <16 for SDR compatibility (!)
3. bump oclif/plugin-plugins for nexus reasons

chore(latest-rc): bump to 7.111.3

---

dockerfiles/Dockerfile_slim

Update `sfdx` installation dir to `/usr/local/sfdx` instead of `~/sfdx` which causes errors for non-root users.
Fixes: https://github.com/forcedotcom/cli/issues/1123
@W-9775541@

chore: update sfdx installation dir in docker slim image

---

package.json

bump to version 7.115.1 and include the SF CLI release candidate

chore(latest-rc): bump to 7.115.1

---

scripts/include-sf.js

- Removes the `path.resolve` when adding in the `sf` path. In CI, this was resolving to a path in the build which doesn't exist on people's machines

fix: dont resolve sf path

---

.circleci/config.yml

Adds missing env var needed for `verify-slim/full-dependencies` command, also enables `verify-full-dependencies` for docker `full` images
@W-9861521@

fix: add missing env var for docker deps verification

---

bin/run-sf
package.json
src/hooks/postupdate.ts

- Adds a script that will execute `sf`. This is preferable to specifying the node_modules sf path for the bin since we can't guarantee that node_modules will exist when npm creates the `sf` executable.
- Better handle errors during postupdate hook
- Add more information to failed sf installs from postupdate hook
**Local Install**
1. `mkdir test-dir && cd test-dir`
2. `npm init`
3. `npm install git+ssh://git@github.com/salesforcecli/sfdx-cli.git#mdonnalley/sf-path`
**Global Install**
1. `npm install -g git+ssh://git@github.com/salesforcecli/sfdx-cli.git#mdonnalley/sf-path`
@W-9875023@
@W-9875088@
@W-9831748@
https://github.com/forcedotcom/cli/issues/1174
https://github.com/forcedotcom/cli/issues/1175

fix: add script to execute sf

---

src/hooks/postupdate.ts

Suggest alternative ways to install `sf` if the postupdate hook fails to install it for the user
```
~/repos/salesforcecli/sfdx-cli [main] : sfdx update
sfdx-cli: Installing sf... failed
Failed to install sf. Try one of the following:
- npm: npm install @salesforce/cli --global
- installer: https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf.pkg
```
@W-9916812@

chore: suggest alternative install paths for failed sf installs

---

package.json

Updates `@salesforce/plugin-templates` to the latest version so the `@salesforce/templates` library that it brings in won't conflict with the one included by `sf` through `@salesforce/plugin-generate`, it should be `52.2.0` in both.
@W-9958398@

fix: update @salesforce/templates to latest

---

scripts/include-sf.js

fix: use absolute path to sf

---

package.json
yarn.lock

Bumps `@salesforce/cli` to 1.0.0

chore: bump sf to 1.0.1

---

package.json
yarn.lock

Fixes an install bug with sf when customer is using internal npm registry w/auth and npm v6
@W-9976179@

fix: update sf dep to 1.0.2

---

package.json
yarn.lock

Adds the plugin-info command to display release notes on the command line
Do not merge this until https://github.com/salesforcecli/plugin-info/pull/33 and https://github.com/salesforcecli/plugin-info/pull/32 are merged.
[@W-10184599@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-10184599)
- Pull branch
- View help `./bin/run info:releasenotes:display -h`
- View notes `./bin/run info:releasenotes:display -v 7.127.0`
- Note that this currently fails without passing a version because of an accidental release (`1.129.0`). This will be resolved after Thursday
- Test alias `./bin/run whatsnew -v 7.127.0`

Add plugin-info

---

package.json

Removes the `postinstall` script so that `@salesforce/cli` is no longer install with sfdx (npm installs only)
@W-10121246@
https://github.com/forcedotcom/cli/issues/1286

chore: remove postinstall of @salesforce/cli

---

.circleci/config.yml

Bumps macos image so that our macos `.pkg` gets latest node LTS.
CircleCI docs:
https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions
@W-8776236@

chore: bump macos image

---

src/hooks/displayReleaseNotes.ts

there's 2 ways into this script
- oclif hook (for `sfdx update`) **changed**
- [npm script](https://github.com/salesforcecli/sfdx-cli/blob/main/scripts/post-install-release-notes.js) (for `npm install -g`) **is unmodified**
This modifies the oclif hook to return a promise, and to `resolve()` on all errors instead of `exit(0)`
The npm script still uses exit(0) because it's not part of the hooks stuff and really is a process that can exit. 
QA: I "released" this on the `dev` sfdx-cli channel (for both installer and npm).  There is no release notes entry for `7.134.0-dev.0` so you *should* get an error logged in the terminal but not an *actual* throw/exit
I tested on installer on mac.  
@W-10419173@

fix: no process.exit(0)

---

package.json
scripts/checkSalesforceDx.ts
src/hooks/salesforcedx-check.ts

warns people when they have a CLI > 7.107 and are running salesforcedx as a user plugin
@W-10260547@
Testing is hard since we block the installation of the evil plugin. `Update` hook only makes sense for installer based CLIs.
1. install the evil plugin
1. find your installed directory.  Mine was `~./.local/share/sfdx/client/current` which is a shortcut to an actual version.  There's a version your last few CLIs.  We'll refer to this as `CurrentCLI`
1. in that repo, under `dist/hooks/verifyPluginVersion` you can remove salesforcedx from the BANNED_PLUGINS array
1. now, `sfdx plugins:install salesforcedx`
1. OPTION 1: In the sfdx-cli repo that you're QAing, execute the script directly via a new TS file in /scripts
1. `import dxCheck from  '../dist/hooks/salesforcedx-check.js'; dxCheck();` …

feat: warn people about salesforcedx during update

---

dockerfiles/Dockerfile_full

docker full uses node lts
@W-10289832@

chore: use node lts in docker-full

---

package.json
yarn.lock

Bumps plugin-release-management to v2.11.1 to remediate transitive dep on trim-newlines@v1.0.0
@W-9960315@

chore: bump rel management to 2.11.1 for testing

---

.circleci/config.yml

Reverts promote-to-latest cron back to `00 16 * * 4`

chore: revert promote-to-latest cron

---

.circleci/config.yml

chore: use release context for dependabot-automerge [skip ci]

---

package.json

Bump a patch version of `sfdx-cli` so that when this is merged `latest-rc` will contain the new version of `sf`'s `latest-rc`.
@W-11048194@

chore(latest-rc): bump to 7.148.3

---

package.json

Adds `@salesforce/schemas` to yarn resolutions so that we always get the newest version
These resolutions get bumped automatically in [plugin-release-management](https://github.com/salesforcecli/plugin-release-management/blob/main/src/commands/cli/latestrc/build.ts#L68)
[W-11048751](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-11048751)

Add schemas to yarn resolutions

---

package.json

tests that we can remove SDR/STL resolutions
current rc-build is gonna bump everything in `resolutsions` to its latest.  We want plugins to selectively be able to update to new SDR/STL major versions.
If this passes (can build tarballs that don't have length problems) I'll move it out of draft.
[@W-10743680@](https://gus.lightning.force.com/a07EE00000rPGopYAG)

test: remove resolutions to help parking-orbit

---

package.json

Reverting https://github.com/salesforcecli/sfdx-cli/pull/568 now that those libraries have been Parking Orbited 🛰️

test: revert resolutions

---

package.json
yarn.lock

bumps plugin-rel-mgmt to remove `@oclif/test` v1 from the dep tree.

chore: bump plugin-rel-mgmt to v3

---

src/hooks/displayReleaseNotes.ts
src/hooks/postupdate.ts
src/hooks/salesforcedx-check.ts
src/versions.js
yarn.lock

replace old cli-ux imports with oclif/core.
We don't ship `cli-ux` with the CLI since 7.136.0 
@W-0@

chore: fix: replace old cli-ux imports

---

bin/run
package.json
yarn.lock

Removes the v8-compile-cache dependency.  It does not support ESM and there's no perf difference when using it.
@W-11573948@

chore: remove v8-compile-cache dependency

---

scripts/run-plugin-nuts.js

Skips the `@salesforce/sfdx-plugin-lwc-test` repo due to API failure. Will revisit after migration to GHA
@w-0@

Skip lwc NUTs because of API 403

---

src/hooks/pluginsPreinstall.ts

**depends on:**: https://github.com/salesforcecli/plugin-trust/pull/306
Makes `sfdx` exit the node process if the `plugins:preinstall:verify:signature` hook fails.
this hook (defined in plugin-trust) ask the user if wants to uninstall an unsigned plugin, if the user doesn't answer `y` in the prompt then the hook throws an error but `sfdx` didn't check for this so even answering `n` will make `plugin-plugins` continue installing an unsigned plugin.
`this.error`
https://github.com/salesforcecli/plugin-trust/blob/d3004720a51b4bef6ecd373f947d35c48f701fa9/src/hooks/verifyInstallSignature.ts#L74
prompt answer check:
https://github.com/salesforcecli/plugin-trust/blob/d3004720a51b4bef6ecd373f947d35c48f701fa9/src/shared/installationVerification.ts#L481
@W-0@

fix: exit process if `verify:signature` hook fails

---

.github/workflows/promoteRCtoLatest.yml

specifies node version with `promote-to-latest` GHA

chore: specify node version for promote to latest GHA

---

dockerfiles/Dockerfile_full
dockerfiles/Dockerfile_slim

Upgrade dockerfile base image from `heroku/heroku:18` to `heroku/heroku:20` to support use of docker container `salesforce/salesforcedx` in GitHub workflows.
```yaml
runs-on: ubuntu-latest
container: salesforce/salesforcedx:latest-rc-full
```
Upgrade the `git` command from version `2.17.1` (bionic) to `2.25.1` (focal) to fix the following error using the GitHub action `actions/checkout`.
```
The repository will be downloaded using the GitHub REST API
To create a local Git repository instead, add Git 2.18 or higher to the PATH
```

fix: bump dockerfile base image to heroku:20 

---

dockerfiles/Dockerfile_full

Updates docker image to use latest node LTS v18.
@W-11955035@

chore(docker): bump node to v18

---

package.json

Pins `plugin-trust` so that it will get bumped weekly on `rc` build
https://salesforce-internal.slack.com/archives/G02K6C90RBJ/p1668527319504199?thread_ts=1665591711.286379&cid=G02K6C90RBJ
@W-00000000

Pin plugin-trust [skip ci]

---

bin/run
src/flags.ts
src/hooks/postupdate.ts
src/versions.js
test/cli.test.ts
test/env.test.ts
test/verifyPluginVersion.test.ts
test/versions.test.ts

adds `--debug-filter` to be used with --dev-debug to filter output
removes ts-lint/es-lint rules that were no longer being broken
@W-12152987@

chore: add --debug-filter and remove ts-lint/es-lint rules where no longer required

---

.github/workflows/makePRforRC.yml

hides the RN from the install scripts via env

ci: hide release notes in pr builds

---

.github/workflows/releaseFail.yml

The failure notification is not firing on failed CLI releases. There seems to be an issue where the `workflow_run` is sometimes missing from the `event` (`github.event.workflow_run.conclusion`)
Using a workaround that was found here: https://github.com/community/community/discussions/21090#discussioncomment-3226271
Also updates the slack text to match repo's failure notifications.
[@W-12369052@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-12369052)

Lookup workflow conclusion

---

.github/workflows/promote.yml

Two things:
- Fixes bad bash substitution
- <img width="727" alt="Screenshot 2023-02-16 at 10 43 55 AM" src="https://user-images.githubusercontent.com/1715111/219433492-6f65a10a-3b2f-493e-946e-ff4c1508d936.png">
- Modifies the `if` on `ctc-proceed` to require previous steps to be successful ([because](https://github.com/salesforcecli/sfdx-cli/actions/runs/4196104397))

Fix bash substituion

---

.github/workflows/just-nuts.yml

runs source nuts using higher parallelism change from plugin-source
open question:
would this code prevent the tests from running when called from the publish job?  
```
if: ${{ !github.event.workflow_run || github.event.workflow_run.conclusion == 'success' }}
```

test: nuts on higher parallelism

---

.github/workflows/create-github-release.yml

`github.ref` is not the current branch on `pull_requests`. You need to use `github.base_ref` instead
See example: https://github.com/iowillhoit/gha-sandbox/actions/runs/4326446315/jobs/7553872132
[@W-12587062@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-12587062)

Correct ref for PRs

---

.github/workflows/create-github-release.yml

Changes the `create-cli-release` trigger to always look for merges. Patches and prereleases will now merge into baseBranches and release from there instead of relying on triggers. See https://github.com/salesforcecli/plugin-release-management/pull/710 for more details
[@W-12654978@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-12654978)

chore: changes patchs to use pr base instead of label

---

.github/workflows/just-nuts.yml

What does this PR do?
Removes a nut call to one that migrated to plugin-deploy-retrieve
What issues does this PR fix or reference?

chore: remove migrated nuts

---

scripts/include-sf.js

`npm install @salesforce/cli@^1` will not install a version higher than what is tagged as `latest` in npm. 
This will list all tags from `npm` and find the **newest** `1.x` version

Get highest 1.x of sf

---

.github/workflows/promote-nightly-to-rc.yml
.github/workflows/promote-rc-to-latest.yml

more retries on promote
https://github.com/salesforcecli/sfdx-cli/actions/runs/4822984865
is there a reason the nightly=>rc is different (bash script?)

ci: retry promote verification for aws cache

---

.gitignore
package.json
yarn.lock

bumps dev-scripts from v3 -> v5 to use latest `eslint-plugin-jsdoc`

chore: use dev-scripts v5

---

package.json
yarn.lock

Removes `@salesforce/ts-types` from `resolutions`. It is already in pinnedDeps

chore: remove ts-types from resolutions

---

.github/workflows/create-github-release.yml

The CLIs do not use conventional-commits to bump the version number in the package.json. Also, the changelogs are not working on the CLIs (see below), because of this I don't think this GHA step is needed. 
--- 
Since we use `skip-version-file: true` with `conventional-changelog-action` on the CLIs, the versions are looked up using `git` . It finds the last tag, and then uses the `releaseType` to determine how to bump it. [Here is an example](https://github.com/salesforcecli/sfdx-cli/actions/runs/5285638613/jobs/9564315511#step:3:1036) of this being incorrect. This is the `create-github-release` run for `7.207.0` where it chose `7.206.7` instead.
Things to consider
* Switch to use conventional commits on the CLI
* Have the `sf-release cli build release` script "tag" the commit message …

Remove change logs

---

scripts/determine-sf-version.js

After `sf` 2.x is `latest`, we can simplify the bundle logic to only ever include the `legacy` version of `sf`.

chore: use legacy sf
